1
EXEC sp_columns DEPT;
select *from DEPT;
2
EXEC sp_columns EMP;
select JOB,HIREDATE,EMPNO from EMP;
3
SELECT ENAME , JOB ,  SAL 'MONTHLY SAL',SAL*12 'ANNUAL SAL'
FROM EMP;
4
SELECT ENAME+','+' '+JOB 'Employee and Title' 
FROM EMP;
5
SELECT DISTINCT job from EMP;
6
SELECT ENAME ,SAL 
FROM EMP
WHERE SAL>2850;
7
SELECT ENAME ,DEPTNO 
FROM EMP
WHERE ENAME='SMITH';
8
SELECT ENAME , JOB 
FROM EMP 
WHERE HIREDATE BETWEEN 'February 20, 1981' AND 'May 1, 1981';
select *from emp;
9
select ename , deptno 
from emp
where DEPTNO in (10,30)
order by ename;
10
select ename ,HIREDATE
from emp
where year(HIREDATE) like '1982%'; 
11
select ename , job 
from emp 
where mgr is null;
12
select cast(getdate() as date);
13
select manager.ename , employee.ename
from emp manager , emp employee
where manager.empno = employee.mgr and manager.HIREDATE < employee.HIREDATE;
15
select ename , DEPTNO
from emp 
where DEPTNO in (20,30,40);
16
select ename
from emp
where ename like 't%r';
17
select ename , HIREDATE
from emp
where DEPTNO = 30;
18
SELECT CONVERT(VARCHAR, HIREDATE, 1) AS 'MM/DD/YY'
FROM EMP;
19
select ename ,HIREDATE
from emp
where year(HIREDATE) like '_____12%'; 
20
select job ,avg(sal*12) avragesal
from emp
group by job;
21
SELECT	JOB,DEPTNO, 
		AVG(SAL*12) AS 'ANNUAL_SAL'
FROM EMP
GROUP BY JOB ,DEPTNO;
22
SELECT	COUNT(SAL) AS 'Salary count',
		COUNT(COMM) AS 'Commission Count'
FROM EMP
WHERE DEPTNO = 30 ;
23
SELECT	AVG(SAL) AS 'AVERAGE salary', 
			MIN(SAL) AS 'MINIMUM salary',
			MAX(SAL) AS 'MAXIMUM salary'
FROM EMP
WHERE JOB = 'CLERK' OR JOB ='MANAGER';
24
SELECT DEPTNO, COUNT(JOB) AS 'CLERK COUNT'
FROM EMP
WHERE JOB = 'CLERK'
GROUP BY DEPTNO;
25
SELECT	ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL*0.3
                 FROM EMP 
                 WHERE JOB= 'PRESIDENT');
26
SELECT COUNT(ENAME)
FROM EMP
JOIN
DEPT
ON LOC='CHICAGO';
27
SELECT ENAME
FROM EMP
JOIN
DEPT
ON LOC='CHICAGO';
28
SELECT e.ENAME, d.LOC
FROM EMP e
JOIN 
DEPT d
ON d.DEPTNO=e.DEPTNO
ORDER BY LOC;
29
SELECT COUNT(DISTINCT DEPTNO)
FROM EMP;
30
SELECT ENAME,
AVG(SAL) AVERAGESALARY
FROM EMP
GROUP BY ENAME;
31
SELECT COUNT(DEPTNO) AS 'No.of Depts'
FROM EMP;
32
SELECT	DISTINCT e.DEPTNO,
		DNAME,
		LOC,
		SUM(COMM) AS TOTALCOMMISSION,
		SUM(SAL) AS TOTOFEACHDEPT
FROM EMP e,DEPT d
GROUP BY e.DEPTNO,DNAME,LOC
ORDER BY DEPTNO;
33
SELECT	ENAME,JOB,
		SAL*12 AS 'SALARY multiplied by 12' 
FROM EMP;
34
SELECT ENAME,JOB,COMM
FROM EMP
WHERE COMM IS NULL;
35
SELECT ENAME,JOB,COMM
FROM EMP
WHERE COMM IS NOT NULL;
36
SELECT	ENAME,JOB,SAL 
FROM EMP 
WHERE ENAME LIKE '__R%'; 
37
SELECT *
FROM EMP
WHERE ENAME LIKE '_____';
38ong.
SELECT *
FROM EMP
WHERE ENAME NOT LIKE '_____';
39
SELECT	* 
FROM EMP 
WHERE ENAME LIKE '%AR%';
40
SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO IN (30)
ORDER BY SAL;
41
SELECT ENAME, SAL
FROM EMP
WHERE SAL BETWEEN 1250 AND 1600;
42
SELECT ENAME, SAL
FROM EMP
WHERE SAL NOT BETWEEN 1250 AND 1600;
43
SELECT SUM(SAL) AS 'TOTAL SALARY OF ALL EMPLOYEES'
FROM EMP;
44
SELECT COUNT(ENAME) AS 'NO.OF EMPLOYEES AS JOB IS NOT NULL'
FROM EMP
WHERE JOB IS NOT NULL;
45
SELECT TOP 1 e.ENAME, MIN(SAL) AS 'MINIMUM SALARY'
FROM EMP e
GROUP BY ENAME;
46
SELECT EMPNO AS 'EMP #',
ENAME AS 'EMPLOYEE',
SAL AS 'SALARY',
JOB AS 'JOB',
HIREDATE AS 'DATE OF HIRE',
COMM AS 'COMMISSION',
DEPTNO AS 'DEPARTMENT NO',
MGR AS 'MGR NO'
FROM EMP;
47
SELECT e.ENAME AS EARLIESTDATE, c.ENAME AS LATESTDATE
FROM EMP e, EMP c
WHERE e.EMPNO = c.MGR and c.HIREDATE < e.HIREDATE;
48
SELECT COUNT(ENAME)AS 'TOTAL NO.OF EMPLOYEES IN DEPT 10',DEPTNO
FROM EMP
WHERE DEPTNO LIKE (10)
GROUP BY DEPTNO;
49
SELECT ENAME,JOB,COMM
FROM EMP e
JOIN DEPT d
ON LOC='New York'
WHERE e.COMM > 10;
50
SELECT DATENAME(WEEKDAY,GETDATE()) 'Day Name', 
FORMAT(GETDATE(), 'mm-dd-yy') AS 'DAY MONTH DD, YYYY'
SELECT DATENAME(WEEKDAY,GETDATE()) 'Day Name', 
FORMAT(GETDATE(), 'dd-mm-yy') AS 'DY DD Mon YYYY'


SELECT DATENAME(WEEKDAY,GETDATE()) 'Day Name', 
FORMAT(GETDATE(), 'yy-mm-dd') AS 'Day ddth Month YYYY';
